### ISSUE TITLE
No effect after enabling spicetify

### ISSUE THREAD

**Issue by varris1** [pietdevries94/spicetify-nix#3]
Hello,
I have tried several ways to install the module (home-manager and via overlay) and tried different themes. 

Sadly the outcome is the same: 
It doesn't affect Spotify at all. I can use Spotify just fine by removing it from `home.packages` and after enabling it via `programs.spicetify` but still I just see the default theme. The symlink in ~/.nix-profiles/bin/spotify is unchanged.

My used config:
```
programs.spicetify = {
    enable = true;
    theme = "Dribbblish";
    colorScheme = "nord-dark";
};
```
is there something I missed?

EDIT:
I found your pull request to nixpkgs and that seems to work just fine, so I'll stick to that

**Comment by pietdevries94** [comment]
I noticed this myself too, but it also fixed itself after a garbage collect. I also don't have any reproduction... Good news your problem got fixed by the PR :)
