### ISSUE TITLE
Maintained and working fork

### ISSUE THREAD

**Issue by the-argus** [pietdevries94/spicetify-nix#7]
[My fork of this repository](https://github.com/the-argus/spicetify-nix) is maintained and working. It supplies a home manager module to flake-based configurations, as well as packaging for many different themes and extensions. If you are trying to get spicetify working on NixOS, use that.

**Comment by pietdevries94** [comment]
Thanks a lot. I haven't been active a lot due to personal reasons. Thanks a lot for letting me know! I shall update the readme to point to your fork!
